# Script generated by Melodia

# load structures
load 1cdoa.pdb
load 1d1ta.pdb
load 1teha.pdb
load 2ohxa.pdb
load 3huda.pdb

# non-conserved cluster color
color gray40

# cluster colors
color 0xd95f02, 1cdoa and resi 15-19
color 0xd95f02, 1d1ta and resi 15-19
color 0xd95f02, 1teha and resi 15-19
color 0xd95f02, 2ohxa and resi 15-19
color 0xd95f02, 3huda and resi 15-19

color 0x7570b3, 1cdoa and resi 23-43
color 0x7570b3, 1d1ta and resi 23-43
color 0x7570b3, 1teha and resi 23-43
color 0x7570b3, 2ohxa and resi 23-43
color 0x7570b3, 3huda and resi 23-43

color 0xe7298a, 1cdoa and resi 45-52
color 0xe7298a, 1d1ta and resi 45-52
color 0xe7298a, 1teha and resi 45-52
color 0xe7298a, 2ohxa and resi 45-52
color 0xe7298a, 3huda and resi 45-52

color 0x66a61e, 1cdoa and resi 56-58

color 0xe6ab02, 1cdoa and resi 67-79
color 0xe6ab02, 1d1ta and resi 67-79
color 0xe6ab02, 1teha and resi 67-79
color 0xe6ab02, 2ohxa and resi 67-79
color 0xe6ab02, 3huda and resi 67-79

color 0xa6761d, 1cdoa and resi 81-88
color 0xa6761d, 1d1ta and resi 81-88
color 0xa6761d, 1teha and resi 81-88
color 0xa6761d, 2ohxa and resi 81-88
color 0xa6761d, 3huda and resi 81-88

color 0x1b9e77, 1cdoa and resi 96-105
color 0x1b9e77, 1d1ta and resi 96-105
color 0x1b9e77, 1teha and resi 96-105
color 0x1b9e77, 2ohxa and resi 96-105
color 0x1b9e77, 3huda and resi 96-105

color 0xd95f02, 1cdoa and resi 108-111
color 0xd95f02, 1teha and resi 108-111

color 0x7570b3, 1d1ta and resi 108-111
color 0x7570b3, 2ohxa and resi 108-111
color 0x7570b3, 3huda and resi 108-111

color 0xe7298a, 1cdoa and resi 122-126

color 0x66a61e, 1d1ta and resi 122-126
color 0x66a61e, 1teha and resi 122-126
color 0x66a61e, 2ohxa and resi 122-126
color 0x66a61e, 3huda and resi 122-126

color 0xe6ab02, 1cdoa and resi 129-260
color 0xe6ab02, 1d1ta and resi 129-260
color 0xe6ab02, 1teha and resi 129-260
color 0xe6ab02, 2ohxa and resi 129-260
color 0xe6ab02, 3huda and resi 129-260

color 0xa6761d, 1cdoa and resi 261-263
color 0xa6761d, 1teha and resi 261-263
color 0xa6761d, 2ohxa and resi 261-263
color 0xa6761d, 3huda and resi 261-263

color 0x1b9e77, 1d1ta and resi 261-263

color 0xd95f02, 1cdoa and resi 264-283
color 0xd95f02, 1d1ta and resi 264-283
color 0xd95f02, 1teha and resi 264-283
color 0xd95f02, 2ohxa and resi 264-283
color 0xd95f02, 3huda and resi 264-283

color 0x7570b3, 1cdoa and resi 285-289
color 0x7570b3, 1d1ta and resi 285-289
color 0x7570b3, 1teha and resi 285-289
color 0x7570b3, 2ohxa and resi 285-289
color 0x7570b3, 3huda and resi 285-289

color 0xe7298a, 1cdoa and resi 291-294
color 0xe7298a, 1d1ta and resi 291-294
color 0xe7298a, 1teha and resi 291-294
color 0xe7298a, 2ohxa and resi 291-294
color 0xe7298a, 3huda and resi 291-294

color 0x66a61e, 1cdoa and resi 295-297

color 0xe6ab02, 1d1ta and resi 295-297
color 0xe6ab02, 1teha and resi 295-297
color 0xe6ab02, 2ohxa and resi 295-297
color 0xe6ab02, 3huda and resi 295-297

color 0xa6761d, 1cdoa and resi 305-312
color 0xa6761d, 1d1ta and resi 305-312
color 0xa6761d, 1teha and resi 305-312
color 0xa6761d, 2ohxa and resi 305-312
color 0xa6761d, 3huda and resi 305-312

color 0x1b9e77, 1cdoa and resi 318-322
color 0x1b9e77, 1d1ta and resi 318-322
color 0x1b9e77, 1teha and resi 318-322
color 0x1b9e77, 2ohxa and resi 318-322
color 0x1b9e77, 3huda and resi 318-322

color 0xd95f02, 1cdoa and resi 324-340
color 0xd95f02, 1d1ta and resi 324-340
color 0xd95f02, 1teha and resi 324-340
color 0xd95f02, 2ohxa and resi 324-340
color 0xd95f02, 3huda and resi 324-340

color 0x7570b3, 1cdoa and resi 343-348
color 0x7570b3, 1d1ta and resi 343-348
color 0x7570b3, 1teha and resi 343-348
color 0x7570b3, 2ohxa and resi 343-348
color 0x7570b3, 3huda and resi 343-348

color 0xe7298a, 1cdoa and resi 350-369
color 0xe7298a, 1d1ta and resi 350-369
color 0xe7298a, 1teha and resi 350-369
color 0xe7298a, 2ohxa and resi 350-369
color 0xe7298a, 3huda and resi 350-369

