# Script generated by Melodia

# load structures
load 1cdoa.pdb
load 1d1ta.pdb
load 1teha.pdb
load 2ohxa.pdb
load 3huda.pdb

# superimpose structures
super 1d1ta, 1cdoa
super 1teha, 1cdoa
super 2ohxa, 1cdoa
super 3huda, 1cdoa

# non-conserved cluster color
color gray40

# cluster colors
color 0x1b9e77, 1cdoa and resi 8-13
color 0x1b9e77, 1d1ta and resi 8-13
color 0x1b9e77, 1teha and resi 8-13
color 0x1b9e77, 2ohxa and resi 8-13
color 0x1b9e77, 3huda and resi 8-13

color 0xd95f02, 1cdoa and resi 24-44
color 0xd95f02, 1d1ta and resi 24-44
color 0xd95f02, 1teha and resi 24-44
color 0xd95f02, 2ohxa and resi 24-44
color 0xd95f02, 3huda and resi 24-44

color 0x7570b3, 1cdoa and resi 46-53
color 0x7570b3, 1d1ta and resi 46-53
color 0x7570b3, 1teha and resi 46-53
color 0x7570b3, 2ohxa and resi 46-53
color 0x7570b3, 3huda and resi 46-53

color 0xe7298a, 1cdoa and resi 57-59

color 0x66a61e, 1d1ta and resi 60-62
color 0x66a61e, 2ohxa and resi 60-62
color 0x66a61e, 3huda and resi 60-62

color 0xe6ab02, 1cdoa and resi 68-70
color 0xe6ab02, 1d1ta and resi 68-70
color 0xe6ab02, 1teha and resi 68-70
color 0xe6ab02, 2ohxa and resi 68-70
color 0xe6ab02, 3huda and resi 68-70

color 0xa6761d, 1cdoa and resi 72-80
color 0xa6761d, 1d1ta and resi 72-80
color 0xa6761d, 1teha and resi 72-80
color 0xa6761d, 2ohxa and resi 72-80
color 0xa6761d, 3huda and resi 72-80

color 0x1b9e77, 1cdoa and resi 82-89
color 0x1b9e77, 1d1ta and resi 82-89
color 0x1b9e77, 1teha and resi 82-89
color 0x1b9e77, 2ohxa and resi 82-89
color 0x1b9e77, 3huda and resi 82-89

color 0xd95f02, 1cdoa and resi 99-106
color 0xd95f02, 1d1ta and resi 99-106
color 0xd95f02, 1teha and resi 99-106
color 0xd95f02, 2ohxa and resi 99-106
color 0xd95f02, 3huda and resi 99-106

color 0x7570b3, 1cdoa and resi 109-111
color 0x7570b3, 1teha and resi 109-111

color 0xe7298a, 1d1ta and resi 109-112
color 0xe7298a, 2ohxa and resi 109-112
color 0xe7298a, 3huda and resi 109-112

color 0x66a61e, 1teha and resi 112-114

color 0xe6ab02, 1cdoa and resi 123-127

color 0xa6761d, 1d1ta and resi 123-127
color 0xa6761d, 1teha and resi 123-127
color 0xa6761d, 2ohxa and resi 123-127
color 0xa6761d, 3huda and resi 123-127

color 0x1b9e77, 1cdoa and resi 130-188
color 0x1b9e77, 1d1ta and resi 130-188
color 0x1b9e77, 1teha and resi 130-188
color 0x1b9e77, 2ohxa and resi 130-188
color 0x1b9e77, 3huda and resi 130-188

color 0xd95f02, 1cdoa and resi 190-261
color 0xd95f02, 1d1ta and resi 190-261
color 0xd95f02, 1teha and resi 190-261
color 0xd95f02, 2ohxa and resi 190-261
color 0xd95f02, 3huda and resi 190-261

color 0x7570b3, 1cdoa and resi 262-264
color 0x7570b3, 1teha and resi 262-264
color 0x7570b3, 2ohxa and resi 262-264
color 0x7570b3, 3huda and resi 262-264

color 0xe7298a, 1d1ta and resi 262-264

color 0x66a61e, 1cdoa and resi 265-284
color 0x66a61e, 1d1ta and resi 265-284
color 0x66a61e, 1teha and resi 265-284
color 0x66a61e, 2ohxa and resi 265-284
color 0x66a61e, 3huda and resi 265-284

color 0xe6ab02, 1cdoa and resi 286-289
color 0xe6ab02, 1d1ta and resi 286-289
color 0xe6ab02, 1teha and resi 286-289
color 0xe6ab02, 2ohxa and resi 286-289
color 0xe6ab02, 3huda and resi 286-289

color 0xa6761d, 1cdoa and resi 292-294
color 0xa6761d, 1d1ta and resi 292-294
color 0xa6761d, 1teha and resi 292-294
color 0xa6761d, 2ohxa and resi 292-294
color 0xa6761d, 3huda and resi 292-294

color 0x1b9e77, 1cdoa and resi 295-298

color 0xd95f02, 1d1ta and resi 295-297
color 0xd95f02, 1teha and resi 295-297
color 0xd95f02, 2ohxa and resi 295-297
color 0xd95f02, 3huda and resi 295-297

color 0x7570b3, 1cdoa and resi 306-313
color 0x7570b3, 1d1ta and resi 306-313
color 0x7570b3, 1teha and resi 306-313
color 0x7570b3, 2ohxa and resi 306-313
color 0x7570b3, 3huda and resi 306-313

color 0xe7298a, 1cdoa and resi 319-323
color 0xe7298a, 1d1ta and resi 319-323
color 0xe7298a, 1teha and resi 319-323
color 0xe7298a, 2ohxa and resi 319-323
color 0xe7298a, 3huda and resi 319-323

color 0x66a61e, 1cdoa and resi 325-341
color 0x66a61e, 1d1ta and resi 325-341
color 0x66a61e, 1teha and resi 325-341
color 0x66a61e, 2ohxa and resi 325-341
color 0x66a61e, 3huda and resi 325-341

color 0xe6ab02, 1cdoa and resi 344-348
color 0xe6ab02, 1d1ta and resi 344-348
color 0xe6ab02, 1teha and resi 344-348
color 0xe6ab02, 2ohxa and resi 344-348
color 0xe6ab02, 3huda and resi 344-348

color 0xa6761d, 1cdoa and resi 353-370
color 0xa6761d, 1d1ta and resi 353-370
color 0xa6761d, 1teha and resi 353-370
color 0xa6761d, 2ohxa and resi 353-370
color 0xa6761d, 3huda and resi 353-370


center
